### ISSUE TITLE
Karma and Todos for Shay Segal

### ISSUE THREAD

**Issue by zvili** [TechnionYP5777/SmartCity-ParkingManagement#10]
_From @shaysegal on October 28, 2016 11:40_

- [X]  Use a picture, photo or distinct avatar. Don''t use an automatic icon:
- [X]  Make sure you present yourself by a readable **nick**
- [X]  Describe yourself in the bio page; FYI, here is my description:
- [X]  State that you are (not) in search for a job, i.e., mark, or unmark this box:

_Copied from original issue: SpartanRefactoring/Spartanizer#558_

**Comment by zvili** [comment]
_From @shaysegal on October 28, 2016 11:41_

can't assgin to myself 
@YossiGil: Done.

**Comment by zvili** [comment]
_From @zahimizrahi on October 28, 2016 11:52_

I'm so astonished from this issue, and it's so scary that you mastered all the tasks. 
you're stepping forward to become the great ruler of GitHub. 💯 

I know that you're a very busy man, but if you can check mine #551 it will make my day.

**Comment by zvili** [comment]
_From @yossigil on October 29, 2016 2:16_

Add a "quality assurance" and "teaching" labels to this issue. Add a deadline (which?). .
 erase much of the junk you copied from the tutorial. Good luck.

**Comment by zvili** [comment]
_From @DavidCohen55 on October 30, 2016 18:40_

![bitmoji](https://render.bitstrips.com/v2/cpanel/9945775-202779545_1-s4-v1.png?transparent=1&width=246)

nice page Shay, check out my page #639 :)

**Comment by zvili** [comment]
_From @AdiOmari on October 30, 2016 20:0_

Good job, please assign yourself to the issue.

**Comment by zvili** [comment]
_From @AdiOmari on November 1, 2016 8:5_

@shaysegal  👍 , But still no teaching and quality assurance labels, add them please.

**Comment by zvili** [comment]
_From @yossigil on November 10, 2016 12:52_

Make sure you use lables @idabran, FYI.

**Comment by shaysegal** [comment]
I currently have two issues that are assigned to me , 
the first is #28 which I work with @sefialbo and second is #29 .
me and @sefialbo  currently learning Pasre and Heroku in order to setup the server .

**Comment by orimarco** [comment]
How would you rank your amount of contribution to the project compared to others in the group?
Please specify the ordinal of the **quintile**.

**Comment by shaysegal** [comment]
I chose to work on the server ,which neither I nor the other members of the team had experience on that subject. although I didn't wrote much java code on the project the server is up(closed issue #28 with @sefialbo) and till next week presentation I plan to finish the tests of the server connection which is exactly what we've promised to Itai and Zvi regarding to the server.

As I understand all the other members of the team are committed to implement what we've promised that will be on next week presentation regarding to their part and as you can see ,each day we commit new work .
