### ISSUE TITLE
Adding TestFX to project 

### ISSUE THREAD

**Issue by zahimizrahi** [TechnionYP5777/SmartCity-ParkingManagement#102]
Testing graphical user interfaces (GUI) requires different or additional testing features than those provided by OO testing framework such as JUnit. 
JavaFX can be affected by various defects such a widget not located at the expected position or a user interaction not working as expected and e.t.c. 

I tried to find for few hours a solution for testing our JavaFX. The best I can come with is [https://github.com/TestFX](TestFX). 

So this issue will be dealing with adding this platform to the project and making basic test to see the platform is working and compatible.

**Comment by ortroyaner** [comment]
Nice!

**Comment by zahimizrahi** [comment]
After hours of spending time trying to make some basic tests in JavaFX, it seems that TestFX doesn't work well and isn't compatible with our project. 
There is still some improvements TestFX needs to do becasue It is very buggy.

I didn't find good framework for testing JavaFX GUI application, so for now - there won't be testing for our GUI. sorry :/ 


Issue is closed.
