### ISSUE TITLE
separate driver and manger functionality on map  

### ISSUE THREAD

**Issue by shaysegal** [TechnionYP5777/SmartCity-ParkingManagement#105]
create two sub classes of PmMap one for driver and one for Manger. 
there are some features that only the driver needs or only the manager needs.

**Comment by shaysegal** [comment]
@tomnof  is there a list of parking area with their location and color? 
i want to add to the ManagerMap list of the of the parking areas
also  @ortroyaner how do you suggest to mark the areas on the map ?

**Comment by tomnof** [comment]
We don't hae a location for parkingArea...
We will hav e name + color if this is what you need. Let me know..

**Comment by shaysegal** [comment]
@tomnof  the location is more the issue because i to display them on the map... so i'll use stubs and next sprint we'll change it

**Comment by tomnof** [comment]
not sure using stubs is a good idea here, since we're not planing on adding a location filed to ParkingArea.
We're working with location per ParkingSlot and not ParkingArea.

Consider using the location of one of the slots in this area?

**Comment by ortroyaner** [comment]
Great issue, thanks.
For the driver main screen we need a static map (a pane/border pane) which will show all the areas available. Each area can be marked with a pin (unique color for each one).
We also want an option to zoom into a specific area.

To sum up:
- Default is a zoom out map where we can see all the area pins.
- When clicking on an area name (from a ViewList or a button - not on the map!), the map should zoom in to that area.
- When clicking on another area, the map should "move" (still with zoom) to the other area.

**Comment by shaysegal** [comment]
@ortroyaner the API for your request is ready, you should be able now to connect it to your controller and test it

**Comment by ortroyaner** [comment]
Thanks shay, what is the name of the function?

**Comment by shaysegal** [comment]
@ortroyaner There's a todo comment in your main controller explaining the API
