### ISSUE TITLE
End of the semester plan

### ISSUE THREAD

**Issue by DavidCohen55** [TechnionYP5777/SmartCity-ParkingManagement#107]
Hey everyone, you're all assigned to this issue so we can plan this **final week of the sprint**.
As you know the sprint is about to end in the 23.1.17, and until this day there are few things we need to discuss:

- [ ] Presentation in 23.1, I need at least one team member from every sub team present the project at the final meeting with the staff.
- [ ] We need to summarize the things we've accomplished in this semester for the report 
- [ ] We need to make a PowerPoint presentation for the 23.1
- [ ] Would we present our project in the 24.1 projects fair?

I think that every sub team should write about what they have done for the project and we will use it to build up the presentation and the final report as the specification we've got in the mail from the staff.
I want that everyone will say what are their priorities from those tasks and I will assign teams in the end for everything.
**Please note that the report need to be in English**
 
Because this isn't going to be an easy task to do while still working on the project code and all of the other assignments we all have for the end of the semester I think that **all of the issues for the sprint need to be done until the 19.1** if someone think that this is too early please comment bellow or contact me.  

just remember its the final countdown for this semester 😄
https://www.youtube.com/watch?v=9jK-NcRmVcw

**Comment by dshames** [comment]
I would like to work on the powerpoint/ summarize the things we've done.

**Comment by Shahar-Y** [comment]
Count me in. @zahimizrahi and I have already discussed on editing the GUI part for the presentation. I'd like to help with this part, as I have no more open issues.

**Comment by zahimizrahi** [comment]
OMG David, I HATE THIS SONG! 💢 

and back to the discussion - I want to work on the presentation & PowerPoint

**Comment by shaysegal** [comment]
@DavidCohen55 finished to write summary on Server & Map. shared it to you and @zahimizrahi  on googleDrive

**Comment by ortroyaner** [comment]
@DavidCohen55 finished to write about manager GUI & external libraries in the report. Also added slides for the presentation.
