### ISSUE TITLE
Adding time fields to GUI

### ISSUE THREAD

**Issue by zahimizrahi** [TechnionYP5777/SmartCity-ParkingManagement#108]
As in issue #92, I want to add functionality of snapshot of the time when the user does logout or exit from the application. @dshames  did the logic for that in #92. what needs to be done is integrating his logic to our GUI part. 

I want that the user could see the last time he logged in as part of myDetails fields.

This issue will be closed when the gui part will show the last time a  user was logged in.

**Comment by Shahar-Y** [comment]
If the git allows me to pull soon, i'll start working on it today

**Comment by Shahar-Y** [comment]
Time fields added, some code was changed in MyDetailsEdit in order to make it more clear and easier to change. Closing issue
