### ISSUE TITLE
Add additional two fields to GUI Management screen

### ISSUE THREAD

**Issue by matityahuinba** [TechnionYP5777/SmartCity-ParkingManagement#111]
hi @ortroyaner ! :wave:
Following issue #93 - 
I notice there are two additional fields that are important and necessary, that did not exist in the previous sketches of the management screen.
These two fields are:
1. _Change "duration type" - permanent\temporary_ 
 The user can change the color of multiple parking slots, either permanently or temporarily. We need to allow the user to choose between only two options. Feel free to choose your favorite implementation; e.g. a dropdown list, radio buttons or any other idea you find suitable.
2. _If the change is temporary_ - the user will insert the end date of the change. After this date the color of the selected parking slots will be restored to their default color.
Note that if the user permanently changes the color, this option is irrelevant.

Thanks!
:heart:

**Comment by zahimizrahi** [comment]
Good idea @matityahuinba 

@ortroyaner  If you need help with your GUI screens, let me know. 🎉

**Comment by ortroyaner** [comment]
Hi, I will need an API for sending and receiving this data to/from the DB (@tomnof for the rescue?). The data is:

- duration type
- expired date
- expired hour (should be separated from the date)

**Comment by ortroyaner** [comment]
<img width="369" alt="screen shot 2017-01-16 at 0 53 37" src="https://cloud.githubusercontent.com/assets/9674645/21966963/46e1d9b8-db86-11e6-9b02-da122964d892.png">

Just created a skeleton for that

**Comment by matityahuinba** [comment]
There is no reason for you to accesses the DB. 
This screen pops up to the user, and when he clicks "Change", you should call the function updateArea() on ManualUpdateArea with the appropriate parameters from the screen.
note that the duration type is enum on data.members.
In addition, we use the type Date which contains the date and hour together, so when sending to function we need to create the new date.
