### ISSUE TITLE
Add Icons to buttons 

### ISSUE THREAD

**Issue by Shahar-Y** [TechnionYP5777/SmartCity-ParkingManagement#115]
As @zahimizrahi  suggested, we will add some cool designed buttons for the GUI screens using the free software inconion. 

@zahimizrahi, make it beautiful :neckbeard: 

https://www.youtube.com/watch?v=eAfyFTzZDMM

**Comment by DavidCohen55** [comment]
@zahimizrahi it was my idea, and also the software I suggested 😠





Just kidding 😆 do a good job 👍

**Comment by zahimizrahi** [comment]
here, take your applause 👏 👏 👏

**Comment by ortroyaner** [comment]
Where do you get the icons? Can you please share?

**Comment by zahimizrahi** [comment]
http://iconion.com/ @ortroyaner

**Comment by shaysegal** [comment]
This issue was moved to TechnionYP5777/SmartParking#12

**Comment by shaysegal** [comment]
migrated to SmartParking project
