### ISSUE TITLE
Handle bad text symbols (Gibberish)

### ISSUE THREAD

**Issue by ortroyaner** [TechnionYP5777/SmartCity-ParkingManagement#116]
some of the characters in the program appear in a wrong way.

<img width="487" alt="screen shot 2017-01-16 at 16 08 13" src="https://cloud.githubusercontent.com/assets/9674645/21985984/01c5698c-dc06-11e6-9de3-1137abe6b228.png">

I'll keep looking for a solution, if anyone saw this before and fixed it, please share a solution 👼

**Comment by shaysegal** [comment]
![image](https://cloud.githubusercontent.com/assets/15847157/21995709/ef0dda6c-dc2e-11e6-943b-421f565b0eee.png)
i see it fine ... on ubuntu probably somthing with encoding

**Comment by matityahuinba** [comment]
Not relevant to this version of the project, has been closed.
