### ISSUE TITLE
Relevant labels

### ISSUE THREAD

**Issue by matityahuinba** [TechnionYP5777/SmartCity-ParkingManagement#120]
As discussed and agreed, those are the labels we will use on this current semester: 

![image](https://cloud.githubusercontent.com/assets/15820085/24322832/9492419e-117c-11e7-832c-2b47acedacb7.png)

**Comment by ortroyaner** [comment]
added label: Vacations

**Comment by tanyabrokhman** [comment]
Not yet discussed or agreed on but its a good start

**Comment by matityahuinba** [comment]
I thought we were supposed to brain storm together and offer ideas in meeting on Monday.
Reopening the issue :blush:

**Comment by matityahuinba** [comment]
As discussed and agreed, those are the **final** labels we will use on this current semester:
![labels2](https://cloud.githubusercontent.com/assets/15820085/24408987/b8d74ed4-13d7-11e7-8657-eabb44a47723.png)

Relevant Wiki page was opened.
