### ISSUE TITLE
Driver Handling - DB

### ISSUE THREAD

**Issue by tomnof** [TechnionYP5777/SmartCity-ParkingManagement#125]
Create infrastructure for adding drivers who park their cars. Relevant information: car number, sticker color, driver email address (notification infrastructure), parking place . 
A lookup table might be used.
Also a function for the gui to use after filling the relevant form.
Delete the existing User class and create a new Driver class
Time estimation :	Delete the old User class (+references) 1-2 hours
                                New DB class : 4-5 hours
			       Adding a new Driver to the system: 5-6 hours

**Comment by matityahuinba** [comment]
Completed.
Relevant issues - #156 #151
