### ISSUE TITLE
Code Coverage

### ISSUE THREAD

**Issue by tomnof** [TechnionYP5777/SmartCity-ParkingManagement#130]
Decide on wanted coverage.
Connect a tool that checks the code coverage and exlude wanted packeges from the total (GUI)
Time estimation : 5-10 hours

**Comment by dshames** [comment]
I will do it. Here is what I have to do in more detail:

- [x] research about the tool CodeCov
- [x] research about the tool ECL
- [x] research about more tools if needed
- [x] choose the preferred tool
- [x] connect the tool to the project
- [x] make the tool calculate the coverage
- [x] exclude wanted packages from the coverage

**Comment by yossigil** [comment]
:100:

**Comment by dshames** [comment]
Finished.
It took me about 14 hours.
