### ISSUE TITLE
Continuous Integration (CI)

### ISSUE THREAD

**Issue by tomnof** [TechnionYP5777/SmartCity-ParkingManagement#131]
Research + implement to make project durable.

**Comment by matityahuinba** [comment]
Research two optional tools –Travis and Sonar Cube – and decide which to use. 
Connect with “Up and Go” for advice :)

**Comment by zahimizrahi** [comment]
You already have travis account in your project that should work fine :)
 (unless you did changes in .travis.yml ... )

**Comment by tomnof** [comment]
@zahimizrahi note that in the way you used Travis, you are not running all the test after each commit (Travis only build for you the project).

Take a look at this to know more :)
http://stackoverflow.com/a/15029935

**Comment by tomnof** [comment]
rellevant commits:
d30b34ba038222515360027213cc000635eab22e
c35b421a46288f4fe73bb023da2f77502ef2e4b5
