### ISSUE TITLE
Instructions on how to run the project

### ISSUE THREAD

**Issue by matityahuinba** [TechnionYP5777/SmartCity-ParkingManagement#134]
- [x] Write a guide that explains how to run the jar – must be done in the upcoming days (ASAP).
- [x] create Wiki page with instructions on how to run the project.

**Comment by ortroyaner** [comment]
It's here:
https://github.com/TechnionYP5777/SmartCity-ParkingManagement/wiki/SmartParking-Part-A---User-Manual

The jar file is uploaded to our git.
