### ISSUE TITLE
Research Graphic presentation

### ISSUE THREAD

**Issue by matityahuinba** [TechnionYP5777/SmartCity-ParkingManagement#135]
Research Graphic presentation on GUI and estimate a deadline for this issue.
According to those findings, we’ll decide if we implement it or not in our next meeting.

**Comment by ortroyaner** [comment]
There is a buit-in pie chart class in java-fx as documented here:
https://docs.oracle.com/javase/8/javafx/api/javafx/scene/chart/PieChart.html
and here:
http://docs.oracle.com/javase/8/javafx/user-interface-tutorial/pie-chart.htm

We should define a base state for each parking area (DB - one more colomn),
and then try to figure out how to save all the parking slots that got changed (maybe a lookup table?) 

We will discuss about the option on the weekly meeting.

**Comment by matityahuinba** [comment]
The study ended.
Graph exists!
