### ISSUE TITLE
Code Cleanup

### ISSUE THREAD

**Issue by tomnof** [TechnionYP5777/SmartCity-ParkingManagement#141]
Clean up the code from last semester - leave only relevant code

**Comment by tomnof** [comment]
@matityahuinba  - please check that Ive dont what we agreed on
@ortroyaner - please go over the GUI code, ther's much of it and I wasn't sure what to delete...

**Comment by matityahuinba** [comment]
Totally agree! :ok_hand:

**Comment by tomnof** [comment]
@ortroyaner - did you had a chance to take a look so we can close this?
