### ISSUE TITLE
Architectural change - parkingArea

### ISSUE THREAD

**Issue by matityahuinba** [TechnionYP5777/SmartCity-ParkingManagement#143]
**Architectural change** - Divide the system to modules:

Change **parkingArea** class according to the architectural change we agreed on.
The class will not change the DB directly, but will activate functions from dbManager class.
**Note** - implementation of tests is also necessary

**Comment by dshames** [comment]
Unfortunately this issue is delayed because we found a problem in the design from last semester, will be discussed in the next meeting.
