### ISSUE TITLE
Architectural change - dbManager

### ISSUE THREAD

**Issue by matityahuinba** [TechnionYP5777/SmartCity-ParkingManagement#145]
**Architectural change** - Divide the system to modules:

This class will handle the DB.
Changes on DB (save new object, update fields, delete an exist object) will occurs only by this class.
Basic functionality –
•	Insert (before inserting a new object, check for duplicates)
•	Delete
•	Update
•	Get fields

Each function includes the parameters: cols names, values, table name
**Note** - implementation of tests is also necessary

**Comment by matityahuinba** [comment]
Hey darling, please note that there is a bug in the function deleteObject :(

**Comment by assaflu** [comment]
I consider this issue close if any problems with the functions comes up open new issue about it and assinge me
