### ISSUE TITLE
Logger usage in existing code

### ISSUE THREAD

**Issue by tomnof** [TechnionYP5777/SmartCity-ParkingManagement#153]
Use the logger in existing code to set convention for future use

**Comment by tomnof** [comment]
@matityahuinba , @assaflu - can you please share the file paths' you worked on?

**Comment by matityahuinba** [comment]
Hi! 👋

- [x] - Driver - /SmartCity-ParkingManagement/src/main/java/data/members/Driver.java
- [x] - ParkingSlot -/SmartCity-ParkingManagement/src/main/java/data/members/ParkingSlot.java
- [x] - Validation -/SmartCity-ParkingManagement/src/main/java/util/Validation.java

Good lock!! :heart:

**Comment by matityahuinba** [comment]
New file added-
- [x] - Order -  /SmartCity-ParkingManagement/src/main/java/logic/Order.java
:)

**Comment by assaflu** [comment]
- [x] - DBManager
- [x] - ParkingSlotRequest (new file)

Good lock!! :heart:
