### ISSUE TITLE
Bug - DBManager.getObjectFieldsByKey

### ISSUE THREAD

**Issue by matityahuinba** [TechnionYP5777/SmartCity-ParkingManagement#159]
Hey Assaf!
That's me again :smile:
I'm not sure, but after testing functions today and yesterday, I think the function DBManager.**getObjectFieldsByKey**(objectClass, key)
has a problem.
If the DB does not find a suitable entry for the parameters entered, the process is stuck and no result is returned (isEmpty doesnt work as we thought).

I'd be happy if you could take a look. :pray:
Thanks!

**Comment by assaflu** [comment]
i will check it out and notify you

**Comment by assaflu** [comment]
I think that the bug is fixed now, I tested it, but please check if your bug is gone. If not notify me in this issue, otherwise close the issue

**Comment by matityahuinba** [comment]
Now the test is passing!
it worked!
Thanks! :satisfied:
