### ISSUE TITLE
group meeting 28/11

### ISSUE THREAD

**Issue by shaysegal** [TechnionYP5777/SmartCity-ParkingManagement#16]
started working on first report and plan the design of the project 
https://docs.google.com/document/d/1htlqyY9_vDIJaxxE_MCyH5IWycpP1WY1ARRDlQGlbpw/edit?usp=sharing

@zvili does the readme file needs to be in english ?

**Comment by zvili** [comment]
1.- The Readme file should be in English.
2.- ALL your reports should reside under the Projects' Wiki. No other type of documents should be used during our course. The course staff will not refer to any other kind of document. :-1:

**Comment by zvili** [comment]
During our first project review (29/11/16) @ 17:15) we want to go over the project user stories.
Your project backlog is still empty ??? :-1:
#13, #14, #11, #9, #8, #12, #10, #15, #7
