### ISSUE TITLE
Fix the build

### ISSUE THREAD

**Issue by assaflu** [TechnionYP5777/SmartCity-ParkingManagement#162]
The build seems to be failing because the time for the test has been exceeded.
In order to lower the test time we can try and use mokito in any classes that test DB function except for the DBManager class.
Since the DBManager class is a singleton it cant be mokot. So I will wrapped the class in a way that will allowed moking, and change the needed class accordingly.

- Since most of the group is in a vication i hope i wont forget any class, but just to cover my self I will create wiki page explaining how to change class so they can be mokot, and how to use mokito in testing

**Comment by yossigil** [comment]
Use a more descriptive title: "Build crash". Your title means nothing and no one know when and if it should be closed.

**Comment by matityahuinba** [comment]
This issue's aim was to stabilize the system in order Travis will pass. Thanks to Assaf, we using Mockito now, and the test run times were shortened by a million! and Travis is passing :)
