### ISSUE TITLE
Changing classes to the new implementation of Database Managing

### ISSUE THREAD

**Issue by assaflu** [TechnionYP5777/SmartCity-ParkingManagement#164]
In issue #163 I create a class that warped DBManager so we can mokc it.
This issue is about changing the classes that uses DBManager:

- [x] - Driver
- [x] - ParkingSlot
- [x] - Order
- [ ] - ParkingSlotRequest

**Comment by assaflu** [comment]
- [ ] - Validation

**Comment by assaflu** [comment]
@matityahuinba after you vication we need to go over the order class to change it, I dont completly understand you code to do it alone. But for now travis run only 6 min so it is ok

**Comment by matityahuinba** [comment]
Begin to work on Order class :)

**Comment by matityahuinba** [comment]
I finished my part :)
Order & OrderTest classes are ready!

**Comment by matityahuinba** [comment]
@assaflu 
We're done, aren't we?
