### ISSUE TITLE
Bug- IlligalMes Test - Notification

### ISSUE THREAD

**Issue by matityahuinba** [TechnionYP5777/SmartCity-ParkingManagement#166]
Hi darling :heart: 

In the testing class **EmailNotificationTest**, there is one test **IlligalMes**  that failed at the running...
I'd be happy if you could take a look. 🙏
Meantime, I remark the test annotation and he would not affect Travis..

Thanks!

**Comment by tomnof** [comment]
I know, already on it :|

**Comment by tomnof** [comment]
I think I configured the Google account in a way this will work. I'm hoping it will catch on every computer and not only mine. 
Pls, let me know if it doesn't (Travis is OK).
Rellevant commits:
247a321643231b2eac302348286dea95c75a1707
5a6e5e851a62d9f41d3162a8e4e527ceb82d2be8
