### ISSUE TITLE
Change in the DataBase column

### ISSUE THREAD

**Issue by assaflu** [TechnionYP5777/SmartCity-ParkingManagement#181]
there is a need to add price to order.
and a need to add review and how many people reviewed a specific slot

**Comment by matityahuinba** [comment]
hi @dshames, @assaflu  !
note that the adding of "price" field to Order is dragging following changes: 
**ChooseParkingSlotController** class - i added a private attribute price and update the function. Initialization to the field must added! (I didnt want to change by myself)
**ParkingSlotRequestTest & ParkingSlotRequest** classes 
please check the correction of the changes
