### ISSUE TITLE
[Final] Bug in registration

### ISSUE THREAD

**Issue by SlasherTech** [TechnionYP5777/SmartCity-ParkingManagement#184]
Seems like no ID is valid for registration.
Can you give an example ?

Anyhow,would be great if you write it in the GUI.

**Comment by matityahuinba** [comment]
Please check the User Manual -
![image](https://user-images.githubusercontent.com/15820085/27768832-3b1a989a-5f25-11e7-8736-eef1145f1cc5.png)

Id field contains, likes in real life, 9 digits.

**Comment by SlasherTech** [comment]
Thanks ! I saw it, but I meant that it would be good if instead of writing "invalid id" to explain what is a valid ID

**Comment by SlasherTech** [comment]
@matityahuinba  can you give me access to write a WIKI page please ? thank you :)

**Comment by matityahuinba** [comment]
@tomnof  is working on it right now :)
