### ISSUE TITLE
[Final] Bug in "Choose time and Data"

### ISSUE THREAD

**Issue by SlasherTech** [TechnionYP5777/SmartCity-ParkingManagement#185]
I am trying to choose time but it seems like it's impossible to change the minutes in the time.
The minute field option is only the current minute.
e.g. : if the time is 12:54, then i can choose only 13:54, 14:54 and so on.

**Comment by dshames** [comment]
Try clicking on the minutes number (54)

**Comment by dshames** [comment]
@MosheEliasof Did it work?

**Comment by matityahuinba** [comment]
@MosheEliasof ?

**Comment by SlasherTech** [comment]
ok , now it works.
i must say it wasnt intuitive at all.

**Comment by matityahuinba** [comment]
its mention on the user guide..
