### ISSUE TITLE
Bug in registraion

### ISSUE THREAD

**Issue by amirsagiv83** [TechnionYP5777/SmartCity-ParkingManagement#186]
I tried to register with a new user, but i didn't get any confirmation mail.

Can you give me an existing user so i can keep working?

**Comment by dshames** [comment]
@amirsagiv83 with what id did you register?

**Comment by amirsagiv83** [comment]
206016009

**Comment by dshames** [comment]
Try using this id with the password you chose in the login screen.
I just tried to log in with you login details and it worked.
Let me know if it works

**Comment by amirsagiv83** [comment]
It works, but still no email. and i didn't went automatically back to login, i had to do it on my own

**Comment by dshames** [comment]
After pressing on CREATE NEW ACCOUNT, did you wait or pressed on the BACK TO LOGIN?
Was there written on the screen that you will get an email?
I just tried to register and got an email, maybe there was a problem with the internet..

**Comment by amirsagiv83** [comment]
ive been waiting 6 7 minutes

it was written in the manual i will get an email

**Comment by matityahuinba** [comment]
@amirsagiv83 , any update? :(

**Comment by tomnof** [comment]
We are closing this issue. If still encounter problems, please notify us.
