### ISSUE TITLE
[Final] Bug in parking order

### ISSUE THREAD

**Issue by SlasherTech** [TechnionYP5777/SmartCity-ParkingManagement#188]
I can order parking of past time

**Comment by SlasherTech** [comment]
![bugorder](https://user-images.githubusercontent.com/23153329/27768891-34e12aaa-5f27-11e7-975d-7e9f6f188376.jpg)

**Comment by dshames** [comment]
Please read our user manual.
It's not a bug, it's a feature!

**Comment by SlasherTech** [comment]
:D
