### ISSUE TITLE
Bug: start time is not the same as ordered

### ISSUE THREAD

**Issue by sefialbo** [TechnionYP5777/SmartCity-ParkingManagement#189]
When I order a parking slot, the start time is always: *:45:26 regardless of the time I chose, I mean the hour is correct, but the minutes and seconds are not.

**Comment by matityahuinba** [comment]
Hi sefi!
Please check the user manual -
![image](https://user-images.githubusercontent.com/15820085/27768940-2754aa28-5f28-11e7-8d2a-b16398cf2312.png)

The order is on the nearest quarter of hours :)

**Comment by yossigil** [comment]
:+1

**Comment by yossigil** [comment]
Just a short note to say I heard much of your sane and wise management of insane situations

@tanyabrokhman
