### ISSUE TITLE
Bug: map doesn't show on order page

### ISSUE THREAD

**Issue by sefialbo** [TechnionYP5777/SmartCity-ParkingManagement#192]
Bug: map doesn't show on order page.
printscreen:
![image](https://user-images.githubusercontent.com/23077518/27768982-f53e7d6a-5f28-11e7-8cad-e89e09ba6137.png)

**Comment by dshames** [comment]
@sefialbo works fine for us and others. Might be internet problems.

**Comment by sefialbo** [comment]
It just started working again, maybe too many requests or internet problems.

**Comment by dshames** [comment]
Great! Closed.
