### ISSUE TITLE
[Final] Bug in pricing

### ISSUE THREAD

**Issue by SlasherTech** [TechnionYP5777/SmartCity-ParkingManagement#193]
I ordered in Ulman 4, it says in the search different price than what i have in the actual order

**Comment by SlasherTech** [comment]
![bugpricing](https://user-images.githubusercontent.com/23153329/27769142-2b925c12-5f2c-11e7-9223-66690cc3c619.png)

**Comment by SlasherTech** [comment]
![bugpricing2](https://user-images.githubusercontent.com/23153329/27769154-56234a9a-5f2c-11e7-8067-96fc195ed716.png)

**Comment by assaflu** [comment]
In the order you made - where the price is 18.98 your destination was "student house" as well? @MosheEliasof

**Comment by SlasherTech** [comment]
yes

**Comment by assaflu** [comment]
I have checked it in my computer now and the price remains the same.
The price for ulman 4 for the "studen house" is 18.04 and for ulman is 18.98

**Comment by assaflu** [comment]
please check again @MosheEliasof

**Comment by assaflu** [comment]
have you checked? @MosheEliasof

**Comment by tomnof** [comment]
We are closing this issue. If you still encounter problems, please notify us.
