### ISSUE TITLE
[Final] Bug in order

### ISSUE THREAD

**Issue by SlasherTech** [TechnionYP5777/SmartCity-ParkingManagement#195]
Price is always the same , no matter how many hours i choose.

**Comment by dshames** [comment]
Thanks! working on it with @tomnof

**Comment by TomPalny** [comment]
Please add label "Final" to this and all other issues from today and yesterday's בוחן מציאות

**Comment by SlasherTech** [comment]
I see that you did work to fix this problem.
Anyway, seems like you still didnt create a new .jar file so I cant test it.
Can you update please ? :)

**Comment by tomnof** [comment]
A new JAR is up :)
