### ISSUE TITLE
[Final] 6 digits car number is not supported in registration

### ISSUE THREAD

**Issue by OmriBS** [TechnionYP5777/SmartCity-ParkingManagement#196]
i have an old car with 6 digits in the license plate and i am not able to register.

**Comment by matityahuinba** [comment]
Although this is not the definition of the project, as written on the user manual
we will change this
@dshames  good luck :)

**Comment by OmriBS** [comment]
thanks.

**Comment by dshames** [comment]
@OmriBS we support 6-7 digit cars. Can you send a picture with the details you tried to register with?

**Comment by OmriBS** [comment]
sorry, i've accidentally put 5 digits number. my bad.
