### ISSUE TITLE
In Register process, empty registration fields give wrong errors

### ISSUE THREAD

**Issue by TomPalny** [TechnionYP5777/SmartCity-ParkingManagement#197]
Hi,
The registration with an empty field gives errors that are not relevant, for example, "Invalid ID" even though the ID is (most likely) vaild, but the rest of the fields are empty.
If the ID is invalid, it should give an indication to what a valid ID should be like.
![image](https://user-images.githubusercontent.com/15875450/27788213-576a24ae-5ff0-11e7-8dc7-e6a2b5f11030.png)

**Comment by TomPalny** [comment]
And now, that the rest of the fields are filled, I still get "invalid ID" error without instructions as to what a valid ID should be like (just as you did in the password field, where you wrote "Password must be at least 6 characters")
![image](https://user-images.githubusercontent.com/15875450/27788320-d3b4ee18-5ff0-11e7-9639-23107833d3bb.png)

**Comment by matityahuinba** [comment]
Hi Tom,
Please check the User Manual -
![image](https://user-images.githubusercontent.com/15820085/27788336-e4d44770-5ff0-11e7-93c2-546d7858e2fb.png)

Its written exactly what are valid values for all the fields.
However, we understand that it is more user friendly 

@dshames can you change?

**Comment by TomPalny** [comment]
I know that it is in the manual, and I read it. However, just as the password field gives an indication to what a valid password should be, the same goes for the ID. As part of the (correct) registration process, this is a "soft error" that should give the user the chance to recover with a more detailed info as to the way to recover from it.

**Comment by dshames** [comment]
We changed the label, a new jar will be uploaded very soon

**Comment by matityahuinba** [comment]
Update change.
Please type **pull** on the command line
And repeat the jar running - 
on the cmd type java -jar "Parking Managment.jar"
please let us know if there is a problem

**Comment by TomPalny** [comment]
Well done!

בתודה,
תום
