### ISSUE TITLE
Telegram group

### ISSUE THREAD

**Issue by zvili** [TechnionYP5777/SmartCity-ParkingManagement#2]
_From @zvili on November 16, 2016 17:56_

_Copied from original issue: TechnionYP5777/SmartCity-ParkingManagement-A#1_

**Comment by zvili** [comment]
- Please define a Telegram group
- Send us your chosen users in Telegram
- Choose a group leader and share with us her/his user name.

**Comment by zahimizrahi** [comment]
it was done, we added everyone. 
telegram group's leader is @DavidCohen55 . 
issue is closed.
