### ISSUE TITLE
Create the Main GUI screen 

### ISSUE THREAD

**Issue by Shahar-Y** [TechnionYP5777/SmartCity-ParkingManagement#23]
The main GUI screen is the one the user sees after logging in (#20). 
It contains a welcoming personal text, asking the user about his next action.
("Hi < username >! What would you like to do next?")
Then, there will be two buttons: 
- A 'Navigate' button, which will lead the user to the 'Choose destination' screen (#25).
- A 'My Details' button which will lead the user to a screen showing the details he entered in the registration screen(#21), and allowing him to change his details. Sends the user to screen #26.

**Comment by zahimizrahi** [comment]
A basic window with all the properties we wanted for this sprint2 - done.
we will probably update the style and the features in the main menu in the future, but I don't see any point keeping this issue open.  😄
