### ISSUE TITLE
Create the "Get Password By Email" GUI screen

### ISSUE THREAD

**Issue by Shahar-Y** [TechnionYP5777/SmartCity-ParkingManagement#24]
This screen will allow a user to get his password by sending him an Email/Notification/SMS (some sort of message), in case he forgot it at the login screen (#20) - by filling in his mail address.
It will contain an 'Edit Text' Line accordingly and a button of 'Send me the password'.
The functionality for Sprint 2 will be basic- meaning there won't be a connection with the server or database.

**Comment by Shahar-Y** [comment]
Get Password By Email screen is ready for presentation. Might be slightly updated in the future, but for now is it done. Closing issue.

**Comment by yossigil** [comment]
Again, take note that there are libraries and frameworks that implement all this

**Comment by Shahar-Y** [comment]
I don't remember you mentioning this, but I will look into it. 
At the moment, we will use what I made for the presentation this week.

**Comment by yossigil** [comment]
News?
