### ISSUE TITLE
Create the "User Details" GUI screen

### ISSUE THREAD

**Issue by zahimizrahi** [TechnionYP5777/SmartCity-ParkingManagement#26]
The user is going to see this page after clicking 'my details' button in the main screen (#23). 
It will contain 'Edit' button which the user can change his/her details.
The details shown in this screen are:

- Username 
- First & Last Name
- Email
- Phone Number
- Car Details:  id, color, company. 
- Sticker Details: exp. data & sticker color. 
- picture (? - optional) 
- and maybe another fields that we will add in the end. 

Note that for Sprint 2 the be a functionality will be basic, meaning that the details won't be stored or changed at the database.

**Comment by Shahar-Y** [comment]
User Details screen is ready for presentation. might be updated in the future, but for now is it done. Closing issue.
