### ISSUE TITLE
setting up the server

### ISSUE THREAD

**Issue by shaysegal** [TechnionYP5777/SmartCity-ParkingManagement#28]
setting up server environment

**Comment by shaysegal** [comment]
deployed an app example on heroku with @sefialbo 
url: https://parking-management.herokuapp.com/

**Comment by shaysegal** [comment]
deployed server dashboard on heroku with @sefialbo 

![dashboard](https://cloud.githubusercontent.com/assets/15847157/21075719/6a39f2c8-bf21-11e6-9040-e9f1a1cfc121.png)

@zvili  @idabran  should I add the server and dashboards files to the git?

**Comment by yossigil** [comment]
Good job!

**Comment by zvili** [comment]
@shaysegal @sefialbo 
Yes, please add thedashboard files to your git repository.
👍

**Comment by sefialbo** [comment]
Server and dashboard are working.
dashboard: https://pm-parse-dashboard.herokuapp.com/apps
