### ISSUE TITLE
Design data model for the server

### ISSUE THREAD

**Issue by sefialbo** [TechnionYP5777/SmartCity-ParkingManagement#30]
Design the data model for the main components: User, ParkingSlot, Manager and ParkingArea.
@dshames @matityahuinba  @tomnof @DavidCohen55

**Comment by zahimizrahi** [comment]
from the code, It looks like it is completed. am I wrong?

**Comment by sefialbo** [comment]
Design+Implementation done in #44

**Comment by yossigil** [comment]
Where is the data model?  It is important that it is clear

**Comment by sefialbo** [comment]
@yossigil We will describe the classes and its related files at #70

**Comment by yossigil** [comment]
thanks.
