### ISSUE TITLE
Implement the data model of the server

### ISSUE THREAD

**Issue by sefialbo** [TechnionYP5777/SmartCity-ParkingManagement#31]
After designing the data model in #30 , Implement the model that was decided.

**Comment by orimarco** [comment]
How would you rank your amount of contribution to the project compared to others in the group?
Please specify the ordinal of the **quintile**.

**Comment by sefialbo** [comment]
@orimarco isn't it suppose to be in the Karma page ?

**Comment by orimarco** [comment]
yes...

**Comment by sefialbo** [comment]
Implementation done in #44

**Comment by yossigil** [comment]
What's the data model of the server?  Where is it implemented?
