### ISSUE TITLE
The system can send or receive data by queries to the databases.

### ISSUE THREAD

**Issue by DavidCohen55** [TechnionYP5777/SmartCity-ParkingManagement#32]
@matityahuinba an I will work together and update this issue:
- [x] Return user
- [x] Return parking slot
- [x] Return parking slot information
- [x] Return user details
- [x] Return parking slots per area
- [x] Return num of users parking in area
- [x] Return num of free parking slots
- [x] Return num of taken parking slots
- [x] Get driver by parking slot
- [x] Return parking slot id by given user

**Comment by matityahuinba** [comment]
All function are writen. 
Next step - Waiting  MongoDB to be set up, and connect to those functions
for real data retrieval

- [x] Return user
- [x] Return parking slot
- [x] Return parking slot information
- [x] Return user details
- [x] Return parking slots per area
- [x] Return num of users parking in area
- [x] Return num of free parking slots
- [x] Return num of taken parking slots
- [x] Get driver by parking slot
- [x] Return parking slot id by given user
