### ISSUE TITLE
When clicking on a parking area, a data on the area will be shown.

### ISSUE THREAD

**Issue by matityahuinba** [TechnionYP5777/SmartCity-ParkingManagement#35]
When clicking on a parking area on the map (or choosing an area on screen, depends if the map which is nice to have will be ready for this sprint), a data of this area will be shown- num of free parking slots, num of taken parking slots, colour of parking area, etc.

- [ ] by clicking specific area, all details of this area will be shown on screen

**Comment by matityahuinba** [comment]
Logic is ready and been tested.
Waiting the demand screen to be completed.

**Comment by zahimizrahi** [comment]
Hi Inbal, 
There is already issue about the gui screens for this logic, there is no need to keep this issue open.

please close it 💘
