### ISSUE TITLE
The user will receive notification about updates and recommandations about parking usage

### ISSUE THREAD

**Issue by matityahuinba** [TechnionYP5777/SmartCity-ParkingManagement#39]
This issue will be implement on next sprints

The user will receive notification about updates about change on classification that the system update dynamically. In addition, the user receive recommandations about parking usage. the user can accept or refuse to the offer.

- [ ] after an update, the message on the update will apear on managment main screen
- [ ] by given information, return recommandation for change of classification
- [ ] accept recommandation
- [ ] refuse recommandation

**Comment by zvili** [comment]
@matityahuinba -  Define assignee & milestone

**Comment by yossigil** [comment]
Indeed...

**Comment by matityahuinba** [comment]
This issue represents a user story that will be dealt with in the upcoming sprints. It was opened because you said to create an issue for any possible user story, but since it is not being currently developed (in the current sprint), no one is assigned to it yet.
We intend to create a work plan for the upcoming sprint in the next meetings, and then these things will be decided :innocent:

**Comment by matityahuinba** [comment]
Not relevant to this version of the project, has been closed.
