### ISSUE TITLE
Preparation Meeting 21.11

### ISSUE THREAD

**Issue by zahimizrahi** [TechnionYP5777/SmartCity-ParkingManagement#4]
Pariticipants:
@Shahar-Y  Shahar Yair 
@dshames  Daniel Shames
@sefialbo   Sefi Albo
@shaysegal  Shay Segal
@DavidCohen55 David Cohen
Zahi Mizrahi 

Summary:
We thought about the main ideas of the project .

it is all described there: https://docs.google.com/document/d/e/2PACX-1vQW_ic4xjzjDsw0L4Rkq6_eziZ-_tijZBC1-fdWSX_jOaWYbJR5YLRxcdnncxtTi6PevEKYbE8ujEm7/pub

**Comment by ortroyaner** [comment]
Translated to English:
https://docs.google.com/document/d/1tls0bY0KRH2MkzKZP6S9HSjSkJSsSoJOu3jCIXObMjE/edit

**Comment by DavidCohen55** [comment]
Daniel Shames(@dshames) and I translated the preparation meeting from 21.11 that has been uploaded by @zahimizrahi  into English. 
it is all described here: https://docs.google.com/document/d/e/2PACX-1vT74utCxiYTuF83GShEJsF4nGt3mVlPnc5zYWut537HdDXmCFGY_C7AVrSUDVBev-n-sP4ua3HeWZwg/pub

**Comment by DavidCohen55** [comment]
Daniel Shames(@dshames) and I translated the preparation meeting from 21.11 that has been uploaded by @zahimizrahi into English.
it is all described here: https://docs.google.com/document/d/e/2PACX-1vT74utCxiYTuF83GShEJsF4nGt3mVlPnc5zYWut537HdDXmCFGY_C7AVrSUDVBev-n-sP4ua3HeWZwg/pub

**Comment by sefialbo** [comment]
Shay Segal(@shaysegal) and I translated the meeting from 28.11 into English:
https://docs.google.com/document/d/1Cm42rzzuB4bE48sivNMrxtMKKN4nGbjUOVjrRMMeaO0/edit?ts=583dcb64
