### ISSUE TITLE
sending/receiving notification email

### ISSUE THREAD

**Issue by DavidCohen55** [TechnionYP5777/SmartCity-ParkingManagement#40]
Will be done in the this sprint:
1. send notification to specific user
2. receive notification to specific user

**Comment by zvili** [comment]
@DavidCohen55 : Define assignee & milestone

**Comment by yossigil** [comment]
indeed...

**Comment by DavidCohen55** [comment]
@zvili @yossigil 
I'm sorry that I didn't do this before, I thought that I already assigned myself.
and about the milestone I didn't knew the date for this, for now it will be to the end of the semester until there will be a better milestone

**Comment by zvili** [comment]
The milestone for the end of the semester is "Sprint 2"

**Comment by DavidCohen55** [comment]
@zvili the milestone was 4.7.17 because this issue isn't intent to be for this sprint, but to another sprint in the future
It doesn't mean that this will be due for 4.7.17, it was like this because there isn't a sprint for this yet

**Comment by sefialbo** [comment]
After discussions with @DavidCohen55 , we decided to leave "notification to all users which their parking slot will be expired" to the next sprint.

**Comment by shaysegal** [comment]
This issue was moved to TechnionYP5777/SmartParking#14

**Comment by shaysegal** [comment]
migrated to SmartParking project
