### ISSUE TITLE
Create data members objects

### ISSUE THREAD

**Issue by tomnof** [TechnionYP5777/SmartCity-ParkingManagement#44]
collect parking data. If none is available, create one that will meet the needs, and will be used as a starting point.

**Comment by tomnof** [comment]
The creation of the data will be taking place while populationg the DB in #45 
This issue is converted to define the data members we'll be using.

**Comment by DavidCohen55** [comment]
In my last commit I uploaded a basic User class that we will use for the database

**Comment by tomnof** [comment]
This issue is closed now since:

- All Classes have been created in the code

- Matching classes have been created (and can be created as we go) in the DB

This is a delicate subject, hence some changes are to be expected, but basically, this is done.
