### ISSUE TITLE
learn about JavaFX + make a small wiki about JavaFX

### ISSUE THREAD

**Issue by zahimizrahi** [TechnionYP5777/SmartCity-ParkingManagement#46]
learn about JavaFX, it's probably the framework we're going to use in this project.
We're gonna watch tutorials on youtube and learn the syntax and skills of this framework. 
We will update the wiki page as well.

- [x] done watching tutorials of javafx framework 

- [x] done writing the wiki pages.

**What is expected:** -  we will know how to make GUIs with JavaFx framework. 
- we will write background about the framework in the wiki of the project.

**Comment by yossigil** [comment]
I think it is better to phrase this 'make a small wiki page for JAVAFX'

**Comment by zahimizrahi** [comment]
@yossigil  as the project continues, we will update the wiki pages so the wiki will become richer. 
we will update about the JavaFX framework as well. 
the goal of this issue is learning about the framework, one of the results will be creating a wiki page for this framework.

**Comment by yossigil** [comment]
- Redefine the isssue so that it is clear what is expected, and how we will know it is done.
- I think it better to have one person and only one for this issue

**Comment by zahimizrahi** [comment]
@yossigil I edited this issue.
also, i opened another issue (#55) related to this issue. 
you can see there the progress of learning more clearly. 
@Shahar-Y  and @ortroyaner  will open issues for their progress as well soon.

**Comment by yossigil** [comment]
:+1:

**Comment by ortroyaner** [comment]
mine is here: #61

**Comment by yossigil** [comment]
You do not have to create wiki pages, an alternative could be `create skeleton of our javaFX application`. The advantge is that you create something that is soon useful. The down side is that you actually have to write code...

**Comment by zahimizrahi** [comment]
since I finished learning JavaFX, and I want the skeleton will divide between the three of us, let's do something like this:
I will do the initial skeleton for driver GUI (already did) 
when @Shahar-Y  will finish he will complete my skeleton of driver GUI.
when @ortroyaner  will finish he will make a skeleton for manager GUI.

**Comment by yossigil** [comment]
:+1:

**Comment by ortroyaner** [comment]
<img width="794" alt="screen shot 2017-01-10 at 18 32 43" src="https://cloud.githubusercontent.com/assets/9674645/21814928/a3b121f2-d763-11e6-9667-1553a1ed3f04.png">

- Graphic Manager GUI skeleton
(I couldn't find a way to upload straight to the wiki page, so I upload here and I'll use the GitHub URL to set this there).


- In addition, the majority of the CODED skeleton is uploaded to the project (still working on it).

**Comment by DavidCohen55** [comment]
Hey guys, it seems that this issue is finished, is there any reason not to close it?
And it seems like the header isn't correct, is it?

**Comment by ortroyaner** [comment]
I have to finish 2 more small screens for the manager skeleton, will be done in a few days.
Thanks for the note about the title, I fixed it.

**Comment by DavidCohen55** [comment]
I think that this page can be about learning javafx and you can open a new issue about the manager skeleton

**Comment by ortroyaner** [comment]
I agree, I'll open new issues for the manager gui skeleton components and i'll close this issue.
- Issue for the skeleton for the main screen is here: #103.
- Issue for the skeleton for the edit screen is here: #96.
- The statistics screen is postponed for the next sprint, since we are not dealing with parking statistics for now.
