### ISSUE TITLE
Fixed map showing Technion parking areas

### ISSUE THREAD

**Issue by ortroyaner** [TechnionYP5777/SmartCity-ParkingManagement#49]
A static map (which will have dynamic areas - the colors of the parking areas) that shows the entire Technion and its parking areas.

**Comment by yossigil** [comment]
I think it better to have one person and only one for this issue

**Comment by zvili** [comment]
@ortroyaner -  Please set a milestone to this issue.

**Comment by matityahuinba** [comment]
Not relevant to this version of the project, has been closed.
