### ISSUE TITLE
Meeting summary 5/12/16

### ISSUE THREAD

**Issue by tomnof** [TechnionYP5777/SmartCity-ParkingManagement#54]
Attendees: Itai & Zvi, David, Shay, Zahi, Or, Dani, Tom, Sefi, Shahar 

At the metting, we went through the final design and concept of the project. 
We looked on several issues for exmaples, and clarify the schedule for the upcoming 6 weeks.
We agreed on the following:
1. In the next two weeks, it is understood that a big part of the team is going to focus on studing and acquiring new technologies (GUI & DB teams mostly). On each new subject, please create a wiki page with a short explanation.
At the end of this two weeks, the team should be able to present the work done so far to the class with a short presentation, Code examples are fine. Also partial work is OK at this part.
2. After Hanukkah, the team should have somthing decent that WORKS and can be presented. There are only two weeks left after the holiday for a final push in this current sprint.

Other things that came up:

- It is ok to have open issues, but it is expected to start seeing closed ones as well. Opening  new issues as we go is fine.

- The concept we created the issues is fine: a well-defined task and a responsible dev assign to it.

At the bottom line - start coding.

**Comment by yossigil** [comment]
Make sure that all studying tasks are reflected as issues, best with deliveries such as:

- Wiki
- Prototype

@idabran @zvili
