### ISSUE TITLE
Zahi Mizrahi - learning JavaFX

### ISSUE THREAD

**Issue by zahimizrahi** [TechnionYP5777/SmartCity-ParkingManagement#55]
related to #46 . 
This issue is about the progress of me learning JavaFX. 
I divide it to some major steps: 

- [x] Step 1: Creating Basic Window

- [x] Step 2: Handle User Events 

- [x] Step 3:  Anonymous Inner Class & Lambda Expressions 

- [x] Step 4:  Switching Scenes 

- [x] Step 5:  Creating Alert Boxes 

- [x] Step 6: Communicating Between Windows 

- [x] Step 7:  Closing the program properly 

- [x] Step 8: Embedding Layouts 

- [x] Step 9: GridPane 

- [x] Step 10:  Extract and Validate Input 

- [x] Step 11:  CheckBox

- [x] Step 12: ChoiceBox (Drop Down Menu)

- [x] Step 13:  Listening for Selection Changes 

- [x] Step 14: ComboBox

- [x] Step 15: ListView

- [x] Step 16:  TreeView 

- [x] Step 17: TableView 

- [x] Step 18: Making Menus 

- [x] Step 19: Handling Menu Clicks 

- [x] Step 20: CheckMenuItem 

- [x] Step 21: RadioMenuitem 

- [x] Step 22: CSS 

- [x] Step 23:  FXML

- [x] Step 24:  SceneBuilder

**Comment by zahimizrahi** [comment]
I finished watching all the tutorials, Issue is closed.

**Comment by yossigil** [comment]
Superb
