### ISSUE TITLE
Use travis for continous build and integration.

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5777/SmartCity-ParkingManagement#58]

**Comment by zahimizrahi** [comment]
@yossigil I need admin access for this repository to enable the project to Travis CI. 
@zvili  can you help?

**Comment by yossigil** [comment]
I delegate to @zvili

**Comment by zvili** [comment]
The project is already access enabled to Travis CI

**Comment by zahimizrahi** [comment]
@yossigil  I talked with @KaplanAlexander , it's not working properly for their project too.

@zvili  can I meet you tomorrow or on monday?

**Comment by yossigil** [comment]
Yes, the right action might be engineering support. Good observation @zahimizrahi

**Comment by zvili** [comment]
@zahimizrahi 
I'm available today Sunday 09:30 – 16:00
And tomorrow Monday 09:30 – 13:00
Please let me know ahead when are we meeting.
Thanks,
Zvi

**Comment by DavidCohen55** [comment]
@zvili 
@zahimizrahi  an I would like to know if we can meet today at 14:30?
If so would it be in your office?

**Comment by zvili** [comment]
Today @ 14:30; my office #209

**Comment by zahimizrahi** [comment]
done 👍
