### ISSUE TITLE
License File

### ISSUE THREAD

**Issue by markrey** [TechnionYP5777/SmartCity-ParkingManagement#59]
Hi,

Great initial efforts.

I would like to checkout the code and may be able to provide some components around real-time sensor integrations.
Would it be possible to add license file? ( Preferably Apache or MIT :) ) 

Thanks

**Comment by yossigil** [comment]
Hi @ortroyaner 

Just placing this on you. Can you please either deal with it, or delegate, or brin to group meeting or whatever.

yg

**Comment by ortroyaner** [comment]
We will talk about it in our next group meeting

**Comment by ortroyaner** [comment]
a license file had been uploaded to the project (Apache 2.0)

**Comment by markrey** [comment]
Thanks a lot @ortroyaner and @yossigil
