### ISSUE TITLE
Preparation meeting -Team B 21/11/16

### ISSUE THREAD

**Issue by matityahuinba** [TechnionYP5777/SmartCity-ParkingManagement#6]
Preparation for full team meeting.
Summary below

https://docs.google.com/document/d/1tls0bY0KRH2MkzKZP6S9HSjSkJSsSoJOu3jCIXObMjE/edit?usp=sharing

**Comment by ortroyaner** [comment]
Meeting Summary:

# Avney Safa Madlikot


**Ideas:**

- Usage statistics - dynamically change of the parking slots type according to the amount of cars with specific sticker color, or according to times and yearly events and holidays.
- To be discussed:
- - Where can we find initial database? Is it fine to fake one? should we save car parking time amount using sensors? How should we update the driver about already parked curbstone color change?

- Manager interface:
GUI for managing parking slots colors manually by:
- - hours
- - dates
- - holidays and events
- - semester periods (exam period, summer etc.)
- - To be discussed: 
- - - Should we give a grace period for drivers whose cars parked while the curbstone was in one color, and now it’s got changed to a not valid curbstone color for his car?
- Proximity sensors:
- - Managing timers for collecting real time statistics.
- - Alerting when curbstone is about to be color changed
- - Blocking color from changing when car is parked in a parking spot.
- - To be discussed:
- - - Is it necessary? Can we get them for the project? How should we transfer data from the sensors to the DB? Are we really want to block color changing when car is parking?
- Users Management:
- - Classifying by sticker’s color.
- - Update sticker color.
- - Adding new users according to user details (name, id etc.)
- - User sticker status (valid or expired).
- - Watch all of the user’s parking tickets. 
- Queries:
- - Given user type (sticker color) and required parking time, the system shall answer the optimized parking slot according to the details above, with guarantee that the slot’s curbstone color will not be changed until the car is parked.
- - Given user type, the system shall show a map of the Technion with all the available parking slots (using proximity sensors).
- - Given a specific parking slot at the Technion, the system shall provide data about the sticker colors who can park there and in what time.
- Map:
- - Graphical and dynamic view of the Technion parking areas, the dynamic colors of the curbstone should be shown as well:
- - - Parking areas colors.
- - - Parking navigation for specific car with specific sticker color.
- - - Update parking’s curbstone color after manual update by Technion Security Unit.
- - - Update parking’s curbstone color after dynamically update by the system.
- Led Lights:
- - Visual change of the curbstone color according to the color it's get by the system.
- - To be discussed:
- - - Is it necessary? Should the system consider a delay, if exists? Do we want to add this kind of a delay? Should we want to block color chaning using the proximity sensors?


First Sprints:
- DB Design.
- Basic design of a GUI for manually management of parking slots.
- Creating DB for users and for parking statistics.
- Creating basic GUI for management.
- Basic diagnostic of the statistics - events, holidays, semester periods.
- Expand diagnostic of the statistics - by hours and days in the week.
