### ISSUE TITLE
Or Troyaner - Learning JavaFX

### ISSUE THREAD

**Issue by ortroyaner** [TechnionYP5777/SmartCity-ParkingManagement#61]
related to #46 . 
This issue is about the progress of me learning JavaFX. 
I divide it to some major steps: 

- [x] Step 1: Creating Basic Window

- [x] Step 2: Handle User Events 

- [x] Step 3:  Anonymous Inner Class & Lambda Expressions 

- [x] Step 4:  Switching Scenes 

- [x] Step 5:  Creating Alert Boxes 

- [x] Step 6: Communicating Between Windows 

- [x] Step 7:  Closing the program properly 

- [x] Step 8: Embedding Layouts 

- [x] Step 9: GridPane 

- [x] Step 10:  Extract and Validate Input 

- [x] Step 11:  CheckBox

- [x] Step 12: ChoiceBox (Drop Down Menu)

- [x] Step 13:  Listening for Selection Changes 

- [x] Step 14: ComboBox

- [x] Step 15: ListView

- [x] Step 16:  TreeView 

- [x] Step 17: TableView 

- [x] Step 18: Making Menus 

- [x] Step 19: Handling Menu Clicks 

- [x] Step 20: CheckMenuItem 

- [x] Step 21: RadioMenuitem 

- [x] Step 22: CSS 

- [x] Step 23:  FXML

- [x] Step 23: Scene Builder

- [x] Step 24: MVC with JavaFX

**Comment by yossigil** [comment]
Excellent job @ortroyaner . This way, you can make this task which is large into something more structured. And, if it is more structured, it is easy to break down, and follow your progress.

@idabran @zvili

**Comment by ortroyaner** [comment]
Thanks but I must say that this idea originally came from @zahimizrahi 's issue #55

**Comment by yossigil** [comment]
Kudus @zahimizrahi then

**Comment by ortroyaner** [comment]
I also learned about using MVC pattern (Model-View-Controller) with JavaFX, thanks to the following tutorials:
1. [MVC, DI with JavaFX with 3 Classes](https://youtu.be/dPLZsc2wSKE)
2. [JavaFX Software Tutorial: Calculator (MVC)](https://youtu.be/y1ZaBalVZic)

(links added to Wiki)
