### ISSUE TITLE
signing up to travis-ci 

### ISSUE THREAD

**Issue by zahimizrahi** [TechnionYP5777/SmartCity-ParkingManagement#62]
How to sign up to travis-ci?

- [ ]  go to https://travis-ci.org 
- [ ]  click 'sign up' 
- [ ] it will open permission to your github. click 'authorize permission'. 
- [ ] enter your password  and you're in!

inform with reply to this issue you are finished.

the issue will be closed when you all are finished.

**Comment by tomnof** [comment]
done!
thanks Zahi 👍

**Comment by yossigil** [comment]
Why does everyone have to do this?

**Comment by zahimizrahi** [comment]
@yossigil  so everyone could take care of the continuous integration and testing. each member will take care of his/her own commits and builds.

**Comment by yossigil** [comment]
does this mean that you get an issue opened or mail sent or something when you break the build?

**Comment by zahimizrahi** [comment]
@yossigil for example, yes. I'm not sure  we will receive mail from travis if the build is broken, we need to check it.

**Comment by tomnof** [comment]
I checked, and:
"By default, email notifications are sent to the committer and the commit author 
...
Emails are sent when, on the given branch:

- a build was just broken or still is broken

- a previously broken build was just fixed
... "

**Comment by yossigil** [comment]
Good point @tomnof

**Comment by matityahuinba** [comment]
Done! :muscle:

**Comment by DavidCohen55** [comment]
Good job @zahimizrahi 👍

**Comment by DavidCohen55** [comment]
Please show that you done this so we can close the issue 😄
- [x] @tomnof 
- [x] @matityahuinba 
- [x] @ortroyaner 
- [x] @dshames 
- [x] @sefialbo 
- [x] @Shahar-Y 
- [x] @shaysegal

**Comment by shaysegal** [comment]
Done

**Comment by Shahar-Y** [comment]
Done

**Comment by dshames** [comment]
DONE

**Comment by yossigil** [comment]
Good job @DavidCohen55

**Comment by ortroyaner** [comment]
Done

**Comment by TomPalny** [comment]
@AdiOmari Check this out, this is involves the same CI issue one of your groups is trying to use

**Comment by AdiOmari** [comment]
@tzjpgit Thanks Tom
