### ISSUE TITLE
Create a Wiki page about parking stickers

### ISSUE THREAD

**Issue by dshames** [TechnionYP5777/SmartCity-ParkingManagement#64]
Hey @tomnof , please create a wiki page about the parking stickers. 
Explain about their types and their hierarchy.

**Comment by tomnof** [comment]
done.
https://github.com/TechnionYP5777/SmartCity-ParkingManagement/wiki/Parking-stickers-hierarchy

**Comment by yossigil** [comment]
Page is empty

**Comment by tomnof** [comment]
@yossigil  - Do you know if there is a way to find it? I created the page yesterday, but it seems something went wrong and now it doesn't exist  :(

**Comment by dshames** [comment]
@tomnof 
https://github.com/TechnionYP5777/SmartCity-ParkingManagement/wiki/6-Parking-stickers-hierarchy

the first url is missing the page number

**Comment by tomnof** [comment]
Nice!

**Comment by yossigil** [comment]
@TOMNOF, yes, I could have fixed it myself if I wanted. There is a search in wiki or google to your site. But, I ususally expect that a student be resourceful enough to do it himself.
