### ISSUE TITLE
create wiki about server

### ISSUE THREAD

**Issue by shaysegal** [TechnionYP5777/SmartCity-ParkingManagement#67]
Write a wiki page about server, libraries using the server ,api etc...

**Comment by yossigil** [comment]
Where is the link to the wiki?

**Comment by shaysegal** [comment]
sorry , 
here is the link : https://github.com/TechnionYP5777/SmartCity-ParkingManagement/wiki/5-Parse-Server-and-Heroku-environment

**Comment by yossigil** [comment]
:+1:
