### ISSUE TITLE
graphic map in GUI

### ISSUE THREAD

**Issue by shaysegal** [TechnionYP5777/SmartCity-ParkingManagement#68]
implement Graphic map of the technion which will be part of the driver gui

**Comment by zahimizrahi** [comment]
Good you chose to use gmaxfx. It's the platform I thought about since it works perfectly with JavaFX. 
Keep the good work!

**Comment by shaysegal** [comment]
thank you zahi , i think you forgot Karma++  :stuck_out_tongue_winking_eye:

**Comment by shaysegal** [comment]
close this issue because map is reasonably implemented. 
if other features will be added we will open issues on them
