### ISSUE TITLE
Fix your milestones and labels

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5777/SmartCity-ParkingManagement#69]
- A milestone should not be labeled by a date
- A milestone should have a date
- You may declare a backlog milestone
- Whend a milestone passes, an action is required
- Do not have labels which represent milestones.
- A milestone name should 

I assign @NetanelFelcher , but you can pass it to to whoever you choose. 

@NetanelFelcher or whoever does this,may wish to do more, and create a Wiki page in the repo that @zvili tells him or her.  This wiki wold be giving general guidelines on how to set milestones, and would not be a cut and paster. It is also possible to create an issue re wiki, and place it in the backlog 

 If this person does not have the time, then this is also OK.

**Comment by zahimizrahi** [comment]
@NetanelFelcher  is not in our project at all. 

Maybe you refer to another project?  another person?

**Comment by DavidCohen55** [comment]
@yossigil, I wanted to understand some thing:

- **Whend a milestone passes, an action is required**, does it mean that the action is closing the issue or is it something else?
- **Do not have labels which represent milestones. a milestone name should**, does it mean that we need to delete the label sprint2 for example from all of our issues and to leave it only in the milestone? 

And about the 4.7.17 label, I changed it to backlog milestone and set the due date for 4.7.17(the end of the next semester until there be a new sprint milestone) like you suggested, is it ok now?

**Comment by zahimizrahi** [comment]
@DavidCohen55  I will answer you. 

@yossigil , you can correct me if I'm wrong.
1. When you open an issue, you must define all the tasks the assignees need to do in order to finish this issue. when a milestone passes, it means that all the tasks needs to be done. 

2. Yes, we need to delete this label.

**Comment by yossigil** [comment]
Let @NetanelFelcher deal with this issue. Do **not** start working on it.

**Comment by zahimizrahi** [comment]
but @NetanelFelcher  is not in our project. I think he's in the "Info-Evaluation" project. 

and @DavidCohen55 & I already did it :(

**Comment by DavidCohen55** [comment]
Also I already did it, because its a blocker...
Didn't I cover everything ?

**Comment by yossigil** [comment]
OOPS, then I got this wrong. This was a member of your group who asked that I would not be posting new issues on Saturday. I thought of giving him a chance this time. I probably got the name wrong. We owe him a big apoogy. Do you the name?

**Comment by zahimizrahi** [comment]
@yossigil  I think you are not refering to the correct project.
