### ISSUE TITLE
Karma and Todos for Sefi Albo

### ISSUE THREAD

**Issue by zvili** [TechnionYP5777/SmartCity-ParkingManagement#7]
_From @sefialbo on October 31, 2016 8:27_

- [x]  Use a picture, photo or distinct avatar. Don''t use an automatic icon.
- [x]  Make sure you present yourself by a readable **nick**
- [x]  Describe yourself in the bio page;
- [x]  State that you are (not) in search for a job

_Copied from original issue: SpartanRefactoring/Spartanizer#666_

**Comment by zvili** [comment]
_From @sefialbo on October 31, 2016 8:28_

@yossigil Done.

**Comment by zvili** [comment]
_From @RoeyMaor on October 31, 2016 9:12_

You should definitely keep up the good work.
you might want to visit: #670

**Comment by zvili** [comment]
_From @dshames on November 7, 2016 14:1_

great issue :+1: 
my karma page #790

**Comment by sefialbo** [comment]
Currently have 3 issues that are assigned to me: #28 #30 and #31. Currently, I am  working with @shaysegal on #28 and learning Parse.
