### ISSUE TITLE
Add 'User' to the DB

### ISSUE THREAD

**Issue by tomnof** [TechnionYP5777/SmartCity-ParkingManagement#71]
Add the functionality that added a User to the DB

**Comment by DavidCohen55** [comment]
Hey Tom, I've already done the user adding to the DB along the login and signup function #33 
so I think that we should close this issue.

**Comment by tomnof** [comment]
Have you tested it worked ?

**Comment by DavidCohen55** [comment]
Yes, you can see all of my current checking in the **test/logic/LoginTest.java**.
