### ISSUE TITLE
Adding functionality to GUI on Login screen

### ISSUE THREAD

**Issue by sefialbo** [TechnionYP5777/SmartCity-ParkingManagement#76]

**Comment by DavidCohen55** [comment]
@sefialbo and I will connect the LoginManager class to the GUI and do this following missions:
- [x] Connect **login** to GUI - done by @sefialbo 
- [x] Connect **information** to GUI - done by @sefialbo 
- [x] Connect **update** to GUI #78
- [x] Connect **register** to GUI #79

you can check the other issues for progress.

**Comment by zahimizrahi** [comment]
the 2 last tasks should be in different issues, since this issue is only connected to login GUI screen.

**Comment by zahimizrahi** [comment]
Moreover, I think the error messages should be informative, e.g, the user will know if it enters a wrong password or wrong car number. 
right now you can't know what you enter wrong between those two fields.

**Comment by DavidCohen55** [comment]
@zahimizrahi you're right, this can be in another issue.
we thought that it can be in the same issue because the methods had been implemented in the same class (**LoginManager.java**)

**Comment by DavidCohen55** [comment]
regarding to your second comment, I told @sefialbo that it should be modified and need to return a value such as that, good eye 👍
