### ISSUE TITLE
Register the user to the system using the GUI

### ISSUE THREAD

**Issue by DavidCohen55** [TechnionYP5777/SmartCity-ParkingManagement#79]
Connect **userSignUp** to GUI

**Comment by zahimizrahi** [comment]
because I finished issue #21, you can continue doing this issue. 
I used listeners and it can be a little confusing,  so I put TODOs in the parts you need to implement the functionality.

**Comment by DavidCohen55** [comment]
I've done this issue and also checked that only valid values are allowed
