### ISSUE TITLE
Load real destinations at gui

### ISSUE THREAD

**Issue by sefialbo** [TechnionYP5777/SmartCity-ParkingManagement#87]
The issue is to load real destinations at GUI "ChooseDestination" class.

**Comment by sefialbo** [comment]
Implemented and checked.

**Comment by shaysegal** [comment]
the GUI Doesn't connect to the locig and this issue block #90

**Comment by sefialbo** [comment]
The GUI does load real destination so this issue is closed.  You are talking about using the logic functions to find the closet parking location, and i just commited that(there will be tests after the db is ready).

**Comment by shaysegal** [comment]
@sefialbo 
tried to run it and got this : 
![image](https://cloud.githubusercontent.com/assets/15847157/21938399/df423a6e-d9c3-11e6-83cb-7f2a8a0b2592.png)
...
i dont think that i can do much with this... can you arrange just one example that work so i'll can see it's working?

**Comment by shaysegal** [comment]
@sefialbo @dshames  not sure under whose jurisdiction is this problem but basiclly the problem is this the label of the gui is not connected to something that the navigation logic function knows... so please take care of it

**Comment by dshames** [comment]
you should talk to @sefialbo he wrote this code

**Comment by sefialbo** [comment]
As I said earlier, this issue is closed and is not related to the functionality you are talking about. You can open a new issue with "BUG" label that explains it.
