### ISSUE TITLE
Freshness of information

### ISSUE THREAD

**Issue by matityahuinba** [TechnionYP5777/SmartCity-ParkingManagement#88]
After running some tests we've noticed that accessing the server DB impacts performance substantially.
Therefore, we need to consider the freshness of the information in the project.
- if we retrieve the information from the server on startup then it may be stale.
- otherwise if we retrieve the information for every interaction with the user this will seriously impact performance.

We should define a guideline for the freshness of the information -a global one (for all operations) or custom for some of the operations.

**Comment by shaysegal** [comment]
How much slow are we talking about? How much time for what amount of data? And did you check if previous tests became slow cause it might be related to something that is done wrong

**Comment by tomnof** [comment]
Im not sure this will be in sprint2. If we want to change the entire way we work with the DB, there will be serious work around it. This have to be consider carefully.

**Comment by yossigil** [comment]
Bad smell here: server is still at toy mode, and too slow? What's going on?

**Comment by tomnof** [comment]
After consulting with the course staff, we have two options ahead:

1. Save most of the data on a local cash, and update the DB once in a while.
disadvantage - from what we can tell now, this requires installing dedicated software on each dev' machine \ will only work on a single dev' machine resulting using a different code depands **how** you use your data. This might be complicated, but seems legit.

2. Understand this is only the 'demo' mode (free mode) of the server, hence, we can't ask for a specific location (or can we?) or more space.

Anyhow, optimization will wait for the next sprint.

**Comment by tomnof** [comment]
@yossigil  hope this answers your question.

**Comment by matityahuinba** [comment]
irrelevant, previous project :)
