### ISSUE TITLE
A route between two points for the driver's map

### ISSUE THREAD

**Issue by dshames** [TechnionYP5777/SmartCity-ParkingManagement#90]
I will write a function that gets as input 2 geo points(source and destination) and returns a driving path between those 2 points that will later be shown on the driver's map.

- [x] learn how to use the GMapsFX
- [x] write the function
- [x] check it's working

**Comment by yossigil** [comment]
Take note this is risky. Shortest path on the road is something waze and other struggle with.

**Comment by dshames** [comment]
@yossigil I'm still not sure how the GMapsFX API works but in some of my previous issues where I used the google maps api for walking/driving distances, the API provided the recommended route based on real time data. I guess (and hope) that the GMapsFX API offers something similar.

Anyway, one of our assumptions in the project was that all navigations are taking place inside the Technion, and since there is almost no traffic in here, I guess the shortest road **in distance** will be enough. Waze tries to offer the shortest road **in time** which depends almost entirely on real time data.

**Comment by yossigil** [comment]
Good point

**Comment by dshames** [comment]
after discussing the way to implement the function, we agreed that shay will do it since he built the map gui and is very familiar with the map properties.

**Comment by shaysegal** [comment]
@dshames  i succeed to send a request for a route and to display it (you can see it after pull my commit) **for now** it's just hard coded request. tomorrow i'll change it to use your function
