### ISSUE TITLE
Adding logic of time fields to login 

### ISSUE THREAD

**Issue by zahimizrahi** [TechnionYP5777/SmartCity-ParkingManagement#92]
**Time is precious. as Benjamin Franklin used to say, _"lost time is never found again"_.** 

This issue will deal with **Time**. Since our system will be used with large number of parking areas and users, we will want to add time fields to all our modules. 

- [x]  **Adding time from last login** - taking snapshot of the time when the user does logout or exit from the application. we can integrate with the db and MyDetails later. You don't need to add it to the GUI yet, just implement a method and field that will save it. we will take care this method will be called in case we do logout or exit the app.

use the library `java.util.Date` (The assignee can use something else if it's compatible). We will need the time in format of Date, hour, minutes, seconds (for now). 

I summon @dshames to this mission. so for now this mission is  on best hands.

Dani, think you can control the time? :neckbeard: 

https://www.youtube.com/watch?v=O2IuJPh6h_A

**Comment by tomnof** [comment]
Hi,
Regarding the Adding time to parking slots:
First of all - you can't deiced on changes to the DB member without consulting with the DB team (meaning - me) first!
Second - we would we like to add 'time' to the parking slot? I cant see any reason with this. Please explain.

**Comment by zahimizrahi** [comment]
@tomnof 
Dani is in LOGIC team, and I didn't mean it have to connect with the db yet.
An issue about integrating it with the database will be added (but I don't think it will be done in this sprint).

**Comment by tomnof** [comment]
Well , every field you insert into this classes are going to go over to the DB ( and if it doesn't, it's probably shouldn't be there since this is a DBMember class).

Anyhow - I still don't understand **why** we need this.

**Comment by zahimizrahi** [comment]
@dshames  @tomnof 
Dani can confirm my opinion, but he can still add the Time classes without integrating it to the db (aka, getting/storing the information in db). 
It's functionality that we thought about in the beggining (and somehow wasn't added to Nice To Have). 

We can live without this, but it will be important for the next issues in order to get statistics on the parking slots. Also, we want to see in myDetails when the user was connected last time. 

I saw your comment on the commit `5dbce43`. I don't see any point to revert it, any functionality added should be welcomed.  😃

**Comment by tomnof** [comment]
I talked with @dshames  earlier and he didn't, 
I'm still confused about what functionality you're after. If you could elaborate that will be appreciated .

I disagree - we don't want **any** functionality, but one that is needed. You don't want to add irrelevant code. (TDD)

**Comment by dshames** [comment]
Done.
Added the needed fields and get/set functions to the User class.
I also added the column to the db.
and I also did that everytime a user logs in to our system, his last login time in the db is updated.
