### ISSUE TITLE
Manually Edit Screens

### ISSUE THREAD

**Issue by matityahuinba** [TechnionYP5777/SmartCity-ParkingManagement#93]
Hi GUI team!
I was going over your issues for the current sprint, and there are 3 screens I'd appreciate if you created :)

**The first screen** allows the user to choose a parking area. After choosing an area, **the second screen** opens. In it, some details about the chosen area will be presented (e.g. total number of parking slots in the area, allowed sticker colors for the area, etc.).
By clicking on a "Manually Edit" button, **third screen** opens, and the management could change the sticker color of the area to amount of slots (note-only if the number of parking slots which are free is satisfied).
Clarification -less screens is a possibility. Maybe consider popup screens?

Attached basic sketches of those screens.
Feel free to change by your own opinion :)

![new doc 2017-01-07 19 28 02_1](https://cloud.githubusercontent.com/assets/15820085/21743686/fe274734-d50f-11e6-9b5a-ad4204f63f2c.jpg)

**Comment by zahimizrahi** [comment]
it will be done in 3 seperated issues - #94, #95 by @Shahar-Y 
#96 by me

**Comment by ortroyaner** [comment]
After a discussion between @zahimizrahi, @Shahar-Y and me, I'll build these screens since it's an integral part of the main manager GUI.
You can keep follow on #94, #95, #96.

**Comment by matityahuinba** [comment]
hi @tomnof ! 👋 
Or needs a function that pulls all of the names of ParkingAreas from the server.
There is only one problem - there is no such field in the ParkingArea table in the DB.
Can the DB team help please?
:grin:

**Comment by tomnof** [comment]
Hi :)
We don't have parkingAreaName but ParkingAreaId. Is this good for you?
I'll try to see how this query can be implemented!

**Comment by matityahuinba** [comment]
We think that referring to parking areas with their names is more natural and intuitive to the user than referring to them with their IDs.

For instance, in the ParkingSlot table in the DB, there is a field called "name", and there are parking slots named "taub1", "taub2", "taub3", etc. This means that these are the first, second, and third parking slots in the ParkingArea named "taub". We want to allow the user to choose his parking area (e.g. the parking area named "taub") from a list of all parking area names :blush:

**Comment by tomnof** [comment]
NP.
Ill add it to the table :)

**Comment by tomnof** [comment]
@ortroyaner  - do you have the area's names already ?

**Comment by ortroyaner** [comment]
No, I think the name should be based about the faculty/building near it. Do you know if there is any documentation that binds aread ID to it's name?

**Comment by tomnof** [comment]
Since this is going to be a unique connection, I don't think its necessary.
But the DB will be 'ready to use' with all the updated data on Friday, so you would be able to view it and decided if its clear or not.

**Comment by tomnof** [comment]
@ortroyaner  - you have a fanction that retrives  all parking areas name.
you can find it under data.members\ParkingAreas.

btw - it already existed (thanks @matityahuinba !) but in a different location. Inbal and I agreed this is more suitable.

**Comment by ortroyaner** [comment]
Thanks, it works!
@matityahuinba - you now have a screen with parking area names from the DB.
btw @tomnof - I suggest to change the names so they will have an uppercase letter at the beginning of each name.
<img width="1082" alt="screen shot 2017-01-14 at 23 55 56" src="https://cloud.githubusercontent.com/assets/9674645/21958353/355d6b98-dab5-11e6-9b00-05e0176a982e.png">

**Comment by tomnof** [comment]
Good comment - fixed.
