### ISSUE TITLE
Create Parking Areas Edit screen for the management GUI

### ISSUE THREAD

**Issue by Shahar-Y** [TechnionYP5777/SmartCity-ParkingManagement#96]
As described in issue #93, the third screen of the management's manually edit feature contains a scrolling list, allowing the manager to manually change the allowed sticker colors in the current parking area.
It has two buttons: 
- The first is a 'Back' button, leading to the screen described in issue #95. 
- The second is the 'Edit' button, which updates the area's sticker color as described.
The issue will be closed when the screen is ready.

**Comment by ortroyaner** [comment]
Hi @matityahuinba @tomnof ,
1. I need an API to get the possible colors (by name, e.g. "Red","Green") from the DB so I will be able to show them on the choosing color screen.
2. I need an API to get the total slots **for each area** (area is going to be the argument), and also the free slots (taken slots I can calculate, is it in the DB too?) so I will be able to show them.

Thanks

**Comment by matityahuinba** [comment]
Hi!
1. Do you need this API only for manual update? If so, do you need a list of all the possible colors, except the current color?
2. These functions already appear in ParkingArea:
you can use area.getSlotsByStatus(ParkingSlotStatus.FREE) which returns all the free slots in area
area.getSlotsByStatus(ParkingSlotStatus.TAKEN) which returns all the taken slots in area

**Comment by ortroyaner** [comment]
1. Maybe there will be other uses for that in the future.
Maybe we should pass all the color, and also the current color, and then in the edit screen there will be an arrow shows that we are changing "fromColor" -> "toColor". What do you think?

2. Thanks, I'll use them.

**Comment by matityahuinba** [comment]
Sounds good.
Function which returns the current color already exist -
you can use the class SelectAnArea which contains all the info you need from the selected area.

The second function I will implement now.

**Comment by matityahuinba** [comment]
Done. Enjoy! :heart:

**Comment by ortroyaner** [comment]
Thanks 😃 working on it

**Comment by ortroyaner** [comment]
<img width="637" alt="screen shot 2017-01-23 at 1 22 08" src="https://cloud.githubusercontent.com/assets/9674645/22187182/648bc67a-e10a-11e6-93f1-bf72ae8a5644.png">
(Changes from last commit)
