### ISSUE TITLE
Fix Tests

### ISSUE THREAD

**Issue by DavidCohen55** [TechnionYP5777/SmartCity-ParkingManagement#99]
I will go through all of my tests files and make sure that they were implemented correctly.
I've already checked few of the other members tests and made a few changes, and now I'm going to work again on my tests

**Comment by zahimizrahi** [comment]
I think you need to just go over your tests, since you don't know what the ones who actually wrote the tests wanted to check.

**Comment by DavidCohen55** [comment]
most of the problematic tests are because of db problems, I'm going over the tests to see what need to be done, I think that maybe I will work with **before** **after** annotations and maybe it will solve few of them, in case of a deeper problem I will update you and the ones who in charge of the logic behind the tests

**Comment by DavidCohen55** [comment]
My tests: LoginTest, UserTest are about 90% coverage due to cases that are errors that shouldn't be reached so I think that this is ok 😄 
I will try to help other team members to fix their problems if they struggle with it.
